# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'rooms.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Selection(object):
    def setupUi(self, Selection):
        Selection.setObjectName("Selection")
        Selection.resize(450, 600)
        self.centralwidget = QtWidgets.QWidget(Selection)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(-100, -180, 640, 897))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("images/main_bg.jpg"))
        self.label.setObjectName("label")
        self.text_chats_label = QtWidgets.QLabel(self.centralwidget)
        self.text_chats_label.setGeometry(QtCore.QRect(50, 20, 231, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setItalic(True)
        font.setUnderline(True)
        self.text_chats_label.setFont(font)
        self.text_chats_label.setStyleSheet("color: rgb(85, 255, 255);")
        self.text_chats_label.setObjectName("text_chats_label")
        self.text_chats = QtWidgets.QListWidget(self.centralwidget)
        self.text_chats.setGeometry(QtCore.QRect(50, 70, 351, 192))
        self.text_chats.setStyleSheet("background-color: rgba(255, 170, 255, 200);")
        self.text_chats.setObjectName("text_chats")
        self.voice_chats = QtWidgets.QListWidget(self.centralwidget)
        self.voice_chats.setGeometry(QtCore.QRect(50, 320, 351, 192))
        self.voice_chats.setStyleSheet("background-color: rgba(255, 170, 255, 200);")
        self.voice_chats.setObjectName("voice_chats")
        self.voice_chats_label = QtWidgets.QLabel(self.centralwidget)
        self.voice_chats_label.setGeometry(QtCore.QRect(50, 270, 231, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setItalic(True)
        font.setUnderline(True)
        self.voice_chats_label.setFont(font)
        self.voice_chats_label.setStyleSheet("color: rgb(85, 255, 255);")
        self.voice_chats_label.setObjectName("voice_chats_label")
        self.create_chat_btn = QtWidgets.QPushButton(self.centralwidget)
        self.create_chat_btn.setGeometry(QtCore.QRect(150, 520, 141, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setItalic(True)
        font.setUnderline(True)
        self.create_chat_btn.setFont(font)
        self.create_chat_btn.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgb(239, 110, 254), stop:1 rgb(85, 255, 255));")
        self.create_chat_btn.setCheckable(False)
        self.create_chat_btn.setDefault(False)
        self.create_chat_btn.setObjectName("create_chat_btn")
        Selection.setCentralWidget(self.centralwidget)

        self.retranslateUi(Selection)
        QtCore.QMetaObject.connectSlotsByName(Selection)

    def retranslateUi(self, Selection):
        _translate = QtCore.QCoreApplication.translate
        Selection.setWindowTitle(_translate("Selection", "MainWindow"))
        self.text_chats_label.setText(_translate("Selection", "Text chats"))
        self.voice_chats_label.setText(_translate("Selection", "Voice chats"))
        self.create_chat_btn.setText(_translate("Selection", "Create a room"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Selection = QtWidgets.QMainWindow()
    ui = Ui_Selection()
    ui.setupUi(Selection)
    Selection.show()
    sys.exit(app.exec_())
